# Generated by Django 3.1.7 on 2021-03-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlalgorithm',
            old_name='parend_endpoint',
            new_name='parent_endpoint',
        ),
    ]
